# Generated by Django 5.2.6 on 2026-04-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('enquiries', '0004_enquiry_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_carts', to='enquiries.enquiry'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
