# Generated by Django 5.2.6 on 2026-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_enquiry_cart_city_cart_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
