# Generated by Django 5.2.6 on 2026-04-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
