# Generated by Django 5.2.6 on 2026-01-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Virja Industries', max_length=255)),
                ('about_us', models.TextField(help_text='HTML allowed')),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed_code', models.TextField(blank=True, help_text='Google Maps Embed Iframe HTML')),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
