# Generated by Django 5.2.6 on 2026-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome class (e.g., fas fa-shipping-fast)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_fallback_title', models.CharField(default='Industrial Excellence', max_length=255)),
                ('hero_fallback_text', models.TextField(default='Premium tools, machinery, and safety equipment for professional applications.')),
                ('features_section_enabled', models.BooleanField(default=True)),
                ('categories_title', models.CharField(default='Browse Categories', max_length=255)),
                ('categories_subtitle', models.CharField(default='Our Collection', max_length=255)),
                ('featured_products_title', models.CharField(default='Featured Products', max_length=255)),
                ('featured_products_subtitle', models.CharField(default='Top Picks', max_length=255)),
                ('brands_title', models.CharField(default='Trusted By Industry Leaders', max_length=255)),
                ('cta_title', models.CharField(default='Ready to Optimize Your Production?', max_length=255)),
                ('cta_text', models.TextField(default='Get custom quotes, technical specifications, and bulk pricing for all your industrial needs.')),
                ('cta_btn_text', models.CharField(default='Request a Quote', max_length=50)),
                ('cta_btn_link', models.CharField(default='/contact/', max_length=255)),
                ('catalog_btn_text', models.CharField(default='Download Catalog', max_length=50)),
                ('catalog_btn_link', models.CharField(default='/catalogs/', max_length=255)),
                ('cta_background_image', models.ImageField(blank=True, null=True, upload_to='home_content/')),
            ],
            options={
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company_info/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='footer_description',
            field=models.TextField(blank=True, help_text='Short description for footer'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='header_email',
            field=models.EmailField(blank=True, help_text='Email for header (if different)', max_length=254),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='header_phone',
            field=models.CharField(blank=True, help_text='Phone number for header (if different)', max_length=50),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_info/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
