# Generated by Django 5.2.6 on 2026-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homefeature_homepagecontent_companyinfo_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, max_length=255)),
                ('email_host_password', models.CharField(blank=True, max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.EmailField(default='noreply@example.com', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
    ]
