# Generated by Django 5.2.6 on 2026-04-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='categories_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='categories_title',
        ),
    ]
