# Generated by Django 5.2.6 on 2026-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_homepagecontent_categories_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='catalog_btn_link',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='catalog_btn_text',
        ),
    ]
