# Generated by Django 5.2.6 on 2026-03-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_is_read_enquiry_is_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
