# Generated by Django 5.2.6 on 2026-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_enquiry_company_name_enquiry_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
